name: Build binaries

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-13, ubuntu-22.04]

    name: ${{ matrix.os }}-build
    runs-on: ${{ matrix.os }}

    steps:
      - uses: lukka/get-cmake@latest

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install OpenCL (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get install -y ocl-icd-opencl-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          cache: true

      - uses: actions/checkout@v3

      - name: Build and Install
        run: |
          cmake -S . -B build -G "Ninja Multi-Config"
          cmake --build build --config Release

      - name: tar binaries to keep file permissions
        working-directory: build
        run: |
          tar -cvf Release.tar Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: XDAQ-RHX ${{ matrix.os }}
          path: build/Release.tar
